<?php

// DO NOT TOUCH THIS IF YOU DO NOT KNOW WHAT YOU ARE DOING
// DO NOT TOUCH THIS IF YOU DO NOT KNOW WHAT YOU ARE DOING

// DO NOT TOUCH THIS IF YOU DO NOT KNOW WHAT YOU ARE DOING
// DO NOT TOUCH THIS IF YOU DO NOT KNOW WHAT YOU ARE DOING
// DO NOT TOUCH THIS IF YOU DO NOT KNOW WHAT YOU ARE DOING
// DO NOT TOUCH THIS IF YOU DO NOT KNOW WHAT YOU ARE DOING
// DO NOT TOUCH THIS IF YOU DO NOT KNOW WHAT YOU ARE DOING
// DO NOT TOUCH THIS IF YOU DO NOT KNOW WHAT YOU ARE DOING

return [
    'app' => [
        'development_mode' => true,
        'version' => 'canary'
    ]
];